# This configuration file ensures that pytest treats the 
# current directory as part of the python path, allowing it to find
# the main_files and packages when running the code.
# Without this setting, pytest may fail to
# locate modules inside the main_files/ package when running tests.

# I used a pytest.ini file because I learned about configuring
# module paths in my CPE 345 Modeling & Simulation class (OMNeT++).
# In that course, we use .ini files to control simulation settings,
# and I applied the same idea here so pytest can correctly find my modules.
[pytest]
pythonpath = .